name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run with env
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: npm run build
          start: npm start
        #env:
          #CYPRESS_REACT_APP_BASE_URL: http://localhost:4000/
          #CYPRESS_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          #CYPRESS_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          #CYPRESS_REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
